services:
  saan.db:
    image: postgis/postgis:16-3.4-alpine
    container_name: saan.db
    #command: -c shared_buffers=256MB -c max_connections=105 -c log_statement=all -c log_destination=stderr
    command: -c shared_buffers=256MB -c max_connections=105
    environment:
      POSTGRES_USER: saan_user
      
      POSTGRES_PASSWORD: saan
      POSTGRES_DB: saan
      PGPORT: 5432
    ports:
      - "54322:5432"
    volumes:
      - saan.db.data:/var/lib/postgresql/data
    networks:
      - antoniocnz-network

volumes:
  saan.db.data:
    driver: local

networks:
  antoniocnz-network:
    driver: bridge